import type { Metadata } from "next";
import { PageIntro, Photo, Priorities, QuoteLink, ContactBanner } from "@/components/sections";
import { photos, serviceAreas } from "@/lib/site";

export const metadata: Metadata = { title: "Residential Cleaning", description: "Residential cleaning for homes in Southwest Virginia and Northwest North Carolina. Explore one-time, recurring, deep, and heavy-duty cleaning with JB Squeaky Cleaners." };

export default function Residential() {
  return <><PageIntro eyebrow="Residential cleaning" title="Come home to a little less on your list."><p>Cleaning for the rooms you live in, the details you notice, and the routine that works for you.</p><p>{serviceAreas.residential}</p></PageIntro>
    <section className="section"><div className="container detail-grid"><div className="detail-photo tall-photo"><Photo src={photos.kitchen} alt="Finished residential kitchen with clean counters and floors" eager /><span className="image-note">A FRESH START AT HOME</span></div><div className="detail-copy"><span className="eyebrow"><span />Your home, your priorities</span><h2>A cleaning plan<br />that fits your home.</h2><p>Choose a one-time visit or talk with us about recurring cleaning. We’ll discuss the rooms, condition, and priorities before shaping your quote.</p><Priorities items={[{title:"Kitchens & bathrooms",text:"Discuss counters, fixtures, floors, and the surfaces you want us to focus on."},{title:"Living spaces",text:"Share your priorities for bedrooms, shared rooms, and everyday floor care."},{title:"A more involved reset",text:"Deep and heavy-duty cleaning are available to discuss for spaces needing extra attention."}]} /><QuoteLink /></div></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span />Choose your rhythm</span><h2>A reset today.<br />A routine for tomorrow.</h2></div><p>Your cleaning needs can change. Tell us whether you need a single visit or an ongoing plan.</p></div><div className="plan-grid"><article><span className="pill">ONE-TIME</span><h3>A fresh start</h3><p>A focused visit when your home needs attention. Share your priorities and preferred timing.</p></article><article><span className="pill">RECURRING</span><h3>A regular rhythm</h3><p>Discuss weekly, every-other-week, or monthly visits and a scope that suits your household.</p></article><article><span className="pill">DEEP & HEAVY-DUTY</span><h3>A bigger reset</h3><p>For buildup or more demanding conditions. Let us know what’s involved so we can discuss the right approach.</p></article></div></div></section>
    <section className="section"><div className="container detail-grid reverse"><div className="detail-photo"><Photo src={photos.floor} alt="Finished wood flooring in a residential living room" /></div><div className="detail-copy"><span className="eyebrow"><span />The spaces that matter</span><h2>Let’s start<br />with your home.</h2><p>Tell us the approximate size, the number of rooms, and the areas you’d most like help with. You don’t need to know every detail to begin the conversation.</p><QuoteLink /></div></div></section><ContactBanner /></>;
}
