import type { Metadata } from "next";
import { PageIntro, Photo, QuoteLink, ContactBanner } from "@/components/sections";
import { photos, serviceAreas } from "@/lib/site";

export const metadata: Metadata = { title: "About Us", description: `Meet JB Squeaky Cleaners, a locally owned and insured cleaning company. ${serviceAreas.description}` };

export default function About() {
  return <><PageIntro eyebrow="About JB Squeaky" title="Local people. A hands-on approach."><p>JB Squeaky Cleaners LLC provides residential and commercial cleaning.</p></PageIntro>
    <section className="section"><div className="container detail-grid"><div className="detail-photo team-photo"><Photo src={photos.crew} alt="Two JB Squeaky cleaning crew members together during a cleaning project" eager /><span className="image-note">THE PEOPLE BEHIND THE CLEAN</span></div><div className="detail-copy"><span className="eyebrow"><span />Meet your local cleaning team</span><h2>Here to help<br />with the real work.</h2><p>We’re locally owned and insured.</p><p><strong>Residential Cleaning:</strong> {serviceAreas.residential}.</p><p><strong>Commercial Cleaning:</strong> {serviceAreas.commercial}.</p><p>Our work includes one-time visits, recurring cleaning plans, and conversations about deep or heavy-duty cleaning. We start by understanding your space and what you need help with.</p><div className="about-facts"><span>Locally owned</span><span>Insured</span><span>Residential & commercial</span></div><QuoteLink /></div></div></section>
    <section className="section soft-section"><div className="container detail-grid reverse"><div className="detail-photo"><Photo src={photos.crewWorking} alt="Two cleaning crew members wearing protective clothing while working in a home" /></div><div className="detail-copy"><span className="eyebrow"><span />Every space has a starting point</span><h2>A respectful<br />conversation first.</h2><p>Every cleaning project begins in a different place. Tell us about your priorities, the current condition of the property, and any particular needs.</p><p>We’ll discuss what’s involved so the cleaning plan reflects the work, whether that’s regular care or a bigger reset.</p></div></div></section><ContactBanner /></>;
}
