import type { Metadata } from "next";
import { PageIntro, Priorities, QuoteLink, ContactBanner } from "@/components/sections";
import { serviceAreas } from "@/lib/site";
import { Icon } from "@/components/icon";

export const metadata: Metadata = { title: "Commercial Cleaning", description: "Commercial cleaning serving all of Virginia & North Carolina. Discuss a one-time or recurring cleaning plan for your business with JB Squeaky Cleaners." };

export default function Commercial() {
  return <><PageIntro eyebrow="Commercial cleaning" title="A cleaner space to get down to business."><p>One-time and recurring cleaning for businesses.</p><p>{serviceAreas.commercial}</p></PageIntro>
    <section className="section"><div className="container commercial-grid"><div className="detail-copy"><span className="eyebrow"><span />Built around your workplace</span><h2>Your business has<br />its own rhythm.</h2><p>Your cleaning plan should reflect it. Tell us about the property, how it’s used, and when cleaning would work best. We’ll discuss the scope before preparing a quote.</p><Priorities items={[{title:"Spaces people use every day",text:"Discuss work areas, shared spaces, restrooms, and floor-care priorities."},{title:"One-time or recurring",text:"Request a focused clean or explore an ongoing cleaning arrangement."},{title:"Additional cleaning needs",text:"Share any buildup or heavy-duty work so we can talk through the requirements."}]} /><QuoteLink /></div><aside className="commercial-panel"><Icon name="building" /><span className="eyebrow light">LET’S TALK ABOUT YOUR SPACE</span><h3>Thoughtful cleaning.<br />A practical plan.</h3><ul><li>Property type & approximate size</li><li>Areas that need attention</li><li>Your preferred frequency</li><li>Access & scheduling needs</li></ul><span className="panel-footnote">Locally owned & insured</span></aside></div></section>
    <section className="section soft-section"><div className="container"><div className="section-heading"><div><span className="eyebrow"><span />Clear expectations from the start</span><h2>Start with the details.<br />Build the right scope.</h2></div><p>No two businesses use their space in the same way. Your quote begins with a conversation about yours.</p></div><div className="steps-grid">{[{title:"The property",text:"Location, approximate square footage, and the kind of business using the space."},{title:"The priorities",text:"Areas to focus on, current conditions, and any deeper cleaning needs."},{title:"The schedule",text:"Preferred timing, cleaning frequency, and how we would access the property."}].map((x,i)=><article className="step" key={x.title}><span className="step-number">0{i+1}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section><ContactBanner /></>;
}
